base:
  image: ubuntu:14.04
  working_dir: /srv
  volumes:
    - .:/srv

sass:
  extends: {'service': 'base'}
  image: ubuntudesign/sass
  command: sass --cache-location /.sass-cache --update static/css --force -E "UTF-8"

web:
  extends: {'service': 'base'}
  build: .
  ports:
    - "8003:5000"
  links:
     - db
db:
  image: postgres

sass-watch:
  extends: {'service': 'sass'}
  command: sass --cache-location /.sass-cache --watch static/css -E "UTF-8"
