db:
  image: postgres
web:
  build: .
  volumes:
    - .:/app
  ports:
    - "8003:5000"
  links:
    - db
sass:
  image: ubuntudesign/sass
  command: sass --debug-info --watch /app/static/css
  volumes:
    - .:/app
